Made the changes In vendor Dashboard
dsciitpatna/sahaayak pull request #117
Opened 2019-05-26 01:28 UTC by ritwizsinha

Fixes #107 

Changes:
1.Added the vendor dashboard

Surge Deployment Link: https://pr-[ADD_PULL_REQUEST_NUMBER]-sahaayak.surge.sh

2019-05-27 07:23 UTC, harsh-jindal commented on src/components/VendorDashboard/VendorDashboard.js
> +  enterLoading = () => {
Where is this been used

2019-05-27 07:25 UTC, harsh-jindal requested changes

2019-05-27 07:25 UTC, harsh-jindal commented on src/components/VendorDashboard/VendorDashboard.js
> +  enterIconLoading = () => {
Remove this function. Not required.

2019-05-27 07:27 UTC, harsh-jindal commented
@ritwizsinha Make the above changes. 
And don't open new PR for the same issue. It is tough to review and it is not a good practice

2019-05-28 12:13 UTC, ritwizsinha commented
Changes done @harsh-jindal

2019-05-28 17:00 UTC, harsh-jindal approved these changes

2019-05-28 17:01 UTC, merged