Made changes in the sidebar
dsciitpatna/sahaayak pull request #128
Opened 2019-05-28 17:00 UTC by ritwizsinha

Fixes #
1.Increased font-size in sidebar
2.Increased width of navbar
3.Increased size of the sidebar button

ge Deployment Link: https://pr-[ADD_PULL_REQUEST_NUMBER]-sahaayak.surge.sh

Screenshots for the change: [Add here screenshots showing the changes.]
![Screenshot from 2019-05-28 22-27-11](https://user-images.githubusercontent.com/43509699/58496683-00cda500-8198-11e9-8408-160a549ca992.png)

2019-05-29 10:55 UTC, harsh-jindal requested changes

2019-05-29 10:55 UTC, harsh-jindal commented on src/components/Navbar/Navbar.css
> +  font-size: 30px!important;
@ritwizsinha Its not a good practice to use !important. Please remove that

2019-05-29 15:58 UTC, ritwizsinha commented
@harsh-jindal Made changes

2019-05-30 10:31 UTC, harsh-jindal approved these changes

2019-05-30 10:31 UTC, merged