Added the vendor listing
dsciitpatna/sahaayak pull request #63
Opened 2019-05-19 15:36 UTC by ritwizsinha

![Vendors](https://user-images.githubusercontent.com/43509699/57984497-f3b70480-7a79-11e9-8d08-604c148e7337.png)

2019-05-19 16:59 UTC, harsh-jindal commented
@Hardik-Agrawal Has already made a PR on it. Please try to coordinate over the issues.

2019-05-20 14:32 UTC, harsh-jindal commented
@ritwizsinha Make it 4 cards instead of 3 and resolve conflicts.

2019-05-20 14:33 UTC, harsh-jindal requested changes

2019-05-20 14:33 UTC, harsh-jindal commented on src/components/Navbar/Navbar.js
> +              <TopVendors />
Add this inside Switch in this way `<Route exact path="/" component={TopVendors} />`
Otherwise it will be visible on all pages

2019-05-20 14:44 UTC, Hardik-Agrawal commented
Okay

On Mon 20 May, 2019, 8:03 PM HarshJindal, <notifications@github.com> wrote:

> *@harsh-jindal* requested changes on this pull request.
> ------------------------------
>
> In src/components/Navbar/Navbar.js
> <https://github.com/dsciitpatna/sahaayak/pull/63#discussion_r285624038>:
>
> > @@ -107,7 +108,9 @@ class Navbar extends Component {
>                  minHeight: 280
>                }}
>              >
> -            <Slideshow />
> +
> +              <Slideshow />
> +              <TopVendors />
>
> Add this inside Switch in this way <Route exact path="/"
> component={TopVendors} />
> Otherwise it will be visible on all pages
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dsciitpatna/sahaayak/pull/63?email_source=notifications&email_token=AKIDU5MANFXG7542GPGMYYLPWKZD5A5CNFSM4HN4XZJ2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZDRE5Y#pullrequestreview-239538807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKIDU5M2QZS5H5RD4BOIMFDPWKZD5ANCNFSM4HN4XZJQ>
> .
>

2019-05-20 20:22 UTC, Hardik-Agrawal commented
I added topvendors component inside the switch as told but that's not
showing on the website until I comment out the slideshow part(topvendors is
added just below slideshow)

On Mon 20 May, 2019, 8:03 PM HarshJindal, <notifications@github.com> wrote:

> *@harsh-jindal* requested changes on this pull request.
> ------------------------------
>
> In src/components/Navbar/Navbar.js
> <https://github.com/dsciitpatna/sahaayak/pull/63#discussion_r285624038>:
>
> > @@ -107,7 +108,9 @@ class Navbar extends Component {
>                  minHeight: 280
>                }}
>              >
> -            <Slideshow />
> +
> +              <Slideshow />
> +              <TopVendors />
>
> Add this inside Switch in this way <Route exact path="/"
> component={TopVendors} />
> Otherwise it will be visible on all pages
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dsciitpatna/sahaayak/pull/63?email_source=notifications&email_token=AKIDU5MANFXG7542GPGMYYLPWKZD5A5CNFSM4HN4XZJ2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZDRE5Y#pullrequestreview-239538807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKIDU5M2QZS5H5RD4BOIMFDPWKZD5ANCNFSM4HN4XZJQ>
> .
>

2019-05-23 06:01 UTC, harsh-jindal commented
@ritwizsinha Are going to finalise this ?

2019-05-25 19:19 UTC, closed without merging